# Generated by Django 4.2.5 on 2023-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ttl',
            field=models.IntegerField(blank=True, default=60),
        ),
    ]
